# .yaml configuration file for the meerkat-backend-interface
# Included in this file are:
#     - The number of SPEAD streams to be processed by each hashpipe instance
#     - The names of each available hashpipe instance, according to convention
#     - The names of all the MeerKAT control and monitoring (CAM) sensors to 
#       be retrieved once on subarray configuration. 
#     - The names of all the MeerKAT CAM sensors to which subscriptions should
#       be made 

# In future, the numer of streams per instance will be calculated according to
# the maximum incoming data rate. 
streams_per_instance: 
- 4

# The names of the available hashpipe instances of the form: 
# <host>/<instance number>
hashpipe_instances:
- blpn0/0
- blpn1/0
- blpn2/0
- blpn3/0
- blpn4/0
- blpn5/0
- blpn6/0
- blpn7/0
- blpn8/0
- blpn9/0
- blpn10/0
- blpn11/0
- blpn12/0
- blpn13/0
- blpn14/0
- blpn15/0
- blpn16/0
- blpn17/0
- blpn18/0
- blpn19/0
- blpn20/0
- blpn21/0
- blpn22/0
- blpn23/0
- blpn24/0
- blpn25/0
- blpn26/0
- blpn27/0
- blpn28/0
- blpn29/0
- blpn30/0
- blpn31/0
- blpn32/0
- blpn33/0
- blpn34/0
- blpn35/0
- blpn36/0
- blpn37/0
- blpn38/0
- blpn39/0
- blpn40/0
- blpn41/0
- blpn42/0
- blpn43/0
- blpn44/0
- blpn45/0
- blpn46/0
- blpn47/0
- blpn48/0
- blpn49/0
- blpn50/0
- blpn51/0
- blpn52/0
- blpn53/0
- blpn54/0
- blpn55/0
- blpn56/0
- blpn57/0
- blpn58/0
- blpn59/0
- blpn61/0
- blpn62/0
- blpn63/0

# Sensors for once-off retrieval on configuration of .
# Each sensor should be of the format: <component>:<full_sensor_name>
# Note: the sensor prefix is included and set permanently as 'wide', since
# BLUSE will always use the full 'wide' mode.
# Locations for subarray numbers should be replaced with {} - e.g.
# cbf_1:cbf_1_wide_sync_time should be included as cbf_{}:cbf_{}_wide_sync_time
once_off:
- sdp_{0}:sdp_{0}_subarray_product_ids
- subarray_{0}:subarray_{0}_streams_wide_antenna_channelised_voltage_centre_frequency
- cbf_{0}:cbf_{0}_wide_antenna_channelised_voltage_n_chans_per_substream
- cbf_{0}:cbf_{0}_wide_antenna_channelised_voltage_spectra_per_heap
- cbf_{0}:cbf_{0}_wide_sync_time
- cbf_{0}:cbf_{0}_wide_antenna_channelised_voltage_n_samples_between_spectra
- cbf_{0}:cbf_{0}_wide_adc_sample_rate
- cbf_{0}:cbf_{0}_wide_input_labelling

# Sensors for subscription
# Of the format: <full_sensor_name>

subscription:
- cbf_{}_pos_request_base_azim
- cbf_{}_pos_request_base_ra
- cbf_{}_pos_request_base_dec
- cbf_{}_pos_request_base_elev
- cbf_{}_offset_ut1
# Using the CBF target sensor as well as an antenna-based sensor as a backup.
- cbf_{}_target
- subarray_{}_observation_activity
- subarray_{}_script_status 
- subarray_{}_streams_wide_antenna_channelised_voltage_input_data_suspect

# Other sensors retrieved separately

# Backup target string sensor (retrieved from antennas in pool_resources):
# <antenna_name>_target 

# Telstate endpoint sensor (constructed from available subarray product IDs):
# sdp_{}_spmc_{array_1_wide_0}_telstate_telstate

# Current list of schedule block IDs (retrieved only on capture-init):
# sched_observation_schedule_1
