# .yaml configuration file for the coordinator.

hashpipe_instances:
- blpn48/0
- blpn49/0
- blpn50/0
- blpn51/0
- blpn52/0
- blpn53/0
- blpn54/0
- blpn55/0
- blpn56/0
- blpn57/0
- blpn58/0
- blpn59/0
- blpn61/0
- blpn62/0
- blpn63/0

sensors_per_antenna:
- data_suspect           

sensors_on_configure:

sensors_cont_update:


 
 

